### ISSUE TITLE
Random crashes at coda.breezy.Breezy.lambda$resetWindDirection$1(Breezy.java:68)

### ISSUE THREAD

**Issue by BurningSulphur** [Coda1552/Breezy#19]
This crash happens randomly after a period of time. I'm not sure what causes it as it has happened while doing different things including being AFK or editing an FTB quest.

This is my crash log: https://mclo.gs/cZf4Tv0
It will only be saved for 90 days after the last view in case the link isn't working.

Stacktrace:
	at coda.breezy.Breezy.lambda$resetWindDirection$1(Breezy.java:68) ~[breezy-1.19.2-1.0.4.jar%23225!/:1.19.2-1.0.4] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at coda.breezy.Breezy.resetWindDirection(Breezy.java:67) ~[breezy-1.19.2-1.0.4.jar%23225!/:1.19.2-1.0.4] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:820) ~[forge-1.19.2-[43](https://mclo.gs/cZf4Tv0#L43).2.6-universal.jar%23288!/:?] {re:mixin,re:classloading}

**Comment by Luke100000** [comment]
I noticed that this got most likely fixed in this commit https://github.com/Coda1552/Breezy/commit/bb8a507301ba2e55b73005112306176f84e0b953 will this version get uploaded?

**Comment by BurningSulphur** [comment]
Just checking in to ask what the ETA for uploading that patch listed above is.

**Comment by BurningSulphur** [comment]
Didn’t mean to press that

**Comment by ghost** [comment]
I'd also like to know how this is going. I'm running a modpack that includes Breezy which runs in 1.18.2, and I doubt that this patch is coming to that version despite how often this crash occurs. Looking at the file in question, I think it's called every Minecraft day, which makes sense, because the crash occurs around every twenty minutes.

**Comment by kuba26038** [comment]
seems this issue is still present, i hope the fixed version will be released soon

**Comment by ghost** [comment]
Oh just letting you guys know that I changed the line as per the big bugfixing commit and I've been using that version with no crashes. I have a feeling the bugfixes were for 1.19 so that's why the 1.18 version isn't fixed.

**Comment by koenigstag** [comment]
@Coda1552 issue fixed in https://github.com/Coda1552/Breezy/pull/22
